src/sales/urls.py
from django.urls import path
from django.conf.urls import url
from .views import *
from . import views

app_name = "sales"
urlpatterns = [
    path("contact_list", contact_list, name="contact_list"),
    path("delegate_list", delegate_list, name="delegate_list"),
    path("create_contact", create_contact, name="create_contact"),
    path("postback", postback, name="postback"),
    path("update_contact/<id>", update_contact1, name="update_contact"),
    path("update_contact1/<id>", update_contact1, name="update_contact1"),
    path("interactions/<id>", interactions, name="interactions"),
    path("interactions1/<id>", interactions1, name="interactions1"),
    path("manage_list", manage_list, name="manage_list"),
    path("order_list", order_list, name="order_list"),
    path("agent_stats", agent_stats, name="agent_stats"),
    path("contact_source_list", ContactSourceList.as_view(), name="contact_source_list"),
    path("create_contact_source", create_contact_source, name="create_contact_source"),
    path("postback", postback_handle, name="postback_handle"),
    path("create_profile", create_profile, name="create_profile"),
]

src/sales/models.py
from django.db import models
from django.utils import timezone
from employer.models import Vacancy
from profiles.models import Profile
from django.conf import settings

class Contact(models.Model):
    first_name = models.CharField(max_length=250, blank=True, verbose_name="Имя")
    last_name = models.CharField(max_length=500, blank=True, verbose_name="Фамилия")
    phone_main = models.CharField(max_length=50, unique=True, verbose_name="Телефон1")
    phone2 = models.CharField(max_length=50,  blank=True, verbose_name="Телефон2")
    viber = models.CharField(max_length=50,  blank=True, verbose_name="Вайбер")
    telegram = models.CharField(max_length=50,  blank=True, verbose_name="Телеграм")
    watsap = models.CharField(max_length=50,  blank=True, verbose_name="Ватсап")
    email = models.CharField(max_length=50, blank=True, verbose_name="Имейл")
    age = models.IntegerField(blank=True, default=0, verbose_name="Возраст")
    sex = models.CharField(max_length=1, blank=True, choices=(("м", "Мужской"), ("ж", "Женский")), verbose_name="Пол")
    is_client = models.BooleanField(default=False)
    in_sales = models.BooleanField(default=True)
    profiles = models.ManyToManyField("SkillProfile", default=None, blank=True, verbose_name="Професии кандидата")
    agent = models.ForeignKey(Profile, on_delete=models.CASCADE, default=1)
    source = models.ForeignKey("ContactSource", on_delete=models.CASCADE, verbose_name="Источник контакта")
    lead_quality = models.IntegerField(default=0, verbose_name="Статус",
                                       choices=((-2, "Отказ"), (-1, "Недозвон"), (0, "Новый"),(101, "ТЕПЛЫЙ НО ОТЛОЖЕННЫЙ ЗВОНОК"),
                                                (1, "Интересно но позже"), (2, "Другая Вакансия"), (3, "Приоритет"),
                                                (102, "Принимает Решение"), (103, "ОЖИДАНИЕ ОПЛАТЫ"), (4,"Сделка")))
    city = models.CharField(max_length=200, default='', blank=True, verbose_name="Город проживания")
    next_contact_date = models.DateTimeField(default='1980-01-01 12:12:12', verbose_name="Дата следующего контакта")
    last_contact_date = models.DateTimeField(default='1980-01-01 12:12:12')
    comment = models.CharField(max_length=1500, blank=True, verbose_name="Анамнез")
    cv_url = models.CharField(max_length=250, blank=True, verbose_name="Ссылка на резюме")
    cv_title = models.CharField(max_length=100, blank=True, verbose_name="Заголовок резюме")
    color = models.CharField(max_length=20, blank=True, verbose_name="Цвет")
    objection = models.ForeignKey("Objection", on_delete=models.CASCADE, default=None, verbose_name="Причина отказа")
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)
    proposed_vacancy = models.ManyToManyField(Vacancy, default=None, blank=True, verbose_name="Предложенные вакансии")
    is_pair = models.BooleanField(default=False, verbose_name="Пара", null=True)

    def __str__(self):
        return self.first_name

class SkillProfile(models.Model):
    name = models.CharField(max_length=50, blank=True, verbose_name="Название профиля")

    def __str__(self):
        return self.name


class Objection(models.Model):
    objection = models.CharField(max_length=100, blank=True, verbose_name="Причина отказа")
    strategy = models.CharField(max_length=1500, blank=True, verbose_name="Как работать с отказом")
    def __str__(self):
        return self.objection

class Interaction(models.Model):
    agent = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    result = models.CharField(max_length=1000, blank=True)
    interaction_date = models.DateTimeField(auto_now=True)
    type = models.CharField(max_length=200, default="звонок",
                            choices=(("звонок", "звонок"),
                                     ("вайбер", "вайбер"),
                                     ("телеграм", "телеграм"),
                                     ("ватсап", "ватсап"),
                                     ("email", "email"),
                                     ("sms", "sms"),
                                     ("автопрозвон", "автопрозвон"))
                            )
    class Meta:
        get_latest_by = 'id'

class Order(models.Model):
    vacancy = models.ForeignKey(Vacancy, on_delete=models.CASCADE)
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)
    interaction = models.OneToOneField(Interaction, on_delete=models.CASCADE)
    sale_agent = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='sale_agent',  default=None)
    provision_agent = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='provision_agent', default=None)
    status = models.CharField(max_length=50, choices=(("waiting","Ожидает оплаты"),("paid","Оплачен"),("approved","Подтвержден")))

class ContactSource(models.Model):
    name = models.CharField(max_length=50, blank=False, verbose_name="Название источника")
    description = models.CharField(max_length=250, blank=False, verbose_name="Описание с примерами")
    potential_profiles = models.ManyToManyField("SkillProfile", default=None, blank=True, verbose_name="Возможные профили")

    def __str__(self):
        return self.name

src/sales/forms.py
from authtools.models import User
from django import forms

from  .services import normalize_phone
from .models import *
from datetime import date
from datetime import timedelta


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        exclude = ['agent', 'in_sales', 'is_client', 'created_at', 'updated_at', 'last_contact_date', 'next_contact_date', 'color', 'cv_url', 'cv_title']
        widgets = {
            'comment': forms.Textarea(attrs={'cols': 45, 'rows': 6}),
        }

    def save(self, user, commit=True):
        inst = super(ContactForm, self).save(commit=False)
        if commit:
            inst.agent = user
            inst.save()
            self.save_m2m()
        return inst

    def clean_phone_main(self):
        phone = self.cleaned_data['phone_main']
        phone = normalize_phone(phone)
        if phone is None:
            raise forms.ValidationError("Номер %s имеет не правильный формат, введите в формате 380ХХ ХХХ ХХ ХХ" %  self.cleaned_data['phone_main'])
        return phone

class AgentForm(forms.Form):

    agent = forms.ChoiceField(choices=[])
    def __init__(self, *args, **kwargs):
        super(AgentForm, self).__init__(*args, **kwargs)
        choices = [(i.pk, i.name) for i in
                   (User.objects.filter(groups__name='Agent') | User.objects.filter(groups__name='SuperAgent'))]
        choices.append((1, "Admin"))
        self.fields['agent'].choices = choices

class AgentStats(AgentForm):
    start_date=forms.DateField(label="Начало периода", widget=forms.TextInput(attrs={'autocomplete':'off'}),
                               initial=date.today()-timedelta(days = 3))
    end_date=forms.DateField(label="Конец периода", widget=forms.TextInput(attrs={'autocomplete':'off'}),
                             initial=date.today()+timedelta(days = 1))
    agent = forms.ChoiceField(choices=[])
    def __init__(self, *args, **kwargs):
        super(AgentForm, self).__init__(*args, **kwargs)
        choices = [(i.pk, i.name) for i in
                   (User.objects.filter(groups__name='Agent') | User.objects.filter(groups__name='SuperAgent'))]
        choices.insert(0, ("all", "Все"))
        self.fields['agent'].choices = choices


class ContactSourceForm(forms.ModelForm):
        class Meta:
            model=ContactSource
            fields='__all__'

class InteractionForm(forms.ModelForm):
    date = forms.DateTimeField(label="Дата сл. контакта",widget=forms.TextInput(attrs={'autocomplete':'off'}))

    class Meta:
        model = Interaction
        exclude = ["agent", "interaction_date", "contact"]
        widgets = {
            'result': forms.Textarea(attrs={'cols': 35, 'rows': 6}),
        }
        labels = {
            "result": "Результат",
            "type": "Тип",
        }

    def save(self, agent, contact, commit=True):
        inst = super(InteractionForm, self).save(commit=False)
        inst.agent = agent
        inst.contact = contact
        if commit:
            inst.save()
            self.save_m2m()
        return inst

    # def __init__(self, data, choices=None, *args, **kwargs):
    #     super(InteractionForm, self).__init__(data, *args, **kwargs)
    #     self.fields['sale_position'] = forms.ChoiceField(choices=choices)

class SkillProfileForm(forms.ModelForm):
    class Meta:
        model = SkillProfile
        fields = '__all__'

src/sales/templates/sales/agent_stats.html
{% extends 'base.html' %}

{% block container %}

<h1>Статистика: {{agent.name}}</h1>
<p><b>Количество взаимодействий</b> {{interactions.count}}</p>
<p><b>Количество продаж</b> {{orders_count}}</p>
<form action="" method="get">
  {{agent_stats_form}}

  <input type="submit" value="Показать">
</form>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Агент</th>
      <th scope="col">Контакт</th>
      <th scope="col">Результат</th>
      <th scope="col">Дата</th>
      <th scope="col">Продажа</th>
    </tr>
  </thead>
  <tbody>
{% for i in interactions %}
    <tr>
      <td>{{ i.agent }} </td>
      <td><a href="{% url 'sales:interactions' i.contact.id  %}">{{ i.contact }}</a></td>
      <td>{{ i.result }}</td>
      <td>{{ i.interaction_date }}</td>
      <td>{{ i.order }}</td>
    </tr>
{% endfor %}
  </tbody>
</table>

<script>
    $("#id_start_date").datetimepicker({
      timepicker:false,
      format:'Y-m-d',
      lang:'ru'
    });

    $("#id_end_date").datetimepicker({
      timepicker:false,
      format:'Y-m-d',
      lang:'ru'
    });
  </script>
{% endblock %}

src/sales/templates/sales/contact_list.html
{% extends 'base.html' %}
{% block container %}
{% load crispy_forms_tags %}
{% load tags %}



<form action="" method="get" class="search-form" style="display:none">
  <div class="row"><div class="col-md-4">
  {% for field in filter.form %}

    {%if forloop.counter|divisibleby:"8" %}
      </div><div class="col-md-4">
    {%endif%}
  <div class="form-group">
    <label for="">{{field.label}}</label>
   {{field}}
  </div>
{%endfor%}
</div></div>
  <button type="submit">Поиск</button>

</form>
<p><button onclick="$('.search-form').toggle()">Фильтр</button> Всего: <b>{{filter.qs.count}}</b></p>
<script>


   $("#id_start_date").datetimepicker({
      timepicker:false,
      format:'m/d/Y',
      lang:'ru'
    });

    $("#id_end_date").datetimepicker({
      timepicker:false,
      format:'m/d/Y',
      lang:'ru'
    });
 </script>

<style>
.fixed_header tbody
{
  display:block;
  overflow:auto;
  height:900px;
  width:100%;
}

.fixed_header thead tr
{
  display:block;
}
</style>

  <div class="row">
  <div class="table-responsive">

<table class="table table-striped fixed_header" >
<thead >
    <tr>
      <th scope="col">#</th>
      <th scope="col" style="width: 10%">Тел </th>
      <th scope="col" style="width: 10%">Имя</th>
      <th scope="col" style="width: 25%">Анамнез</th>
      <th style="width: 25%">
        Результат
      </th>
      <th scope="col">Сл. Звон.
        <a href="{% url 'sales:contact_list'%}?order=-next_contact_date">&darr;</a>
        <a href="{% url 'sales:contact_list'%}?order=next_contact_date">&uarr;</a>
      </th>
      <th scope="col" style="width: 10%">Резюме</th>
      <th scope="col" style="width: 10%">Професия</th>
      <th scope="col" style="width: 10%">Ист
       <a href="{% url 'sales:contact_list'%}?order=-source__name">&darr;</a>
         <a href="{% url 'sales:contact_list'%}?order=source__name">&uarr;</a>
      </th>
    </tr>
  </thead>
  <tbody >

{% for c in contact_list %}

    {% with next_element=contact_list|next:forloop.counter0 %}
    {% with previous_element=contact_list|previous:forloop.counter0 %}
    <tr>
      <th  scope="row" style="background-color: {{c.color}}">{{forloop.counter}}</th>
      <td style="width: 10%"> <a href="{% url 'sales:update_contact' c.id  %}?index={{forloop.counter0}}&contacts_id_list={{contacts_id_list}}&count={{count}}">{{c.phone_main|truncatechars:15}}</a></td>
      <td style="width: 10%" data-toggle="tooltip" data-placement="top" title="{{ c.first_name}} {{ c.last_name}}">
         {{ c.first_name|truncatechars:10}} {{ c.last_name|truncatechars:10}}</td>
      <td style="width: 25%" data-toggle="tooltip" data-placement="top" title="{{c.comment}}">{{ c.comment|truncatechars:100 }}</td>
      <td style="width: 25%">{{ c.interaction_set.latest.result }}</td>
      <td >{{ c.next_contact_date|date:"d.m.y"}}</td>
      <td ><a href="{{c.cv_url}}">{{c.cv_title}}</a></td>
      <td style="width: 10%">{% for p in  c.profiles.all %} {{p}} {%endfor%}</td>
      <td style="width: 10%" data-toggle="tooltip" data-placement="top" title="{{c.source.description}} {{ c.source }}">{{ c.source|truncatechars:3}}</td>
    </tr>
    {% endwith %}
    {% endwith %}

{% endfor %}
  </tbody>
  </table>
    {% if contact_list.has_other_pages %}
<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if contact_list.has_previous %}
    <li class="page-item"><a class="page-link" href="?{% param_replace page=contact_list.previous_page_number %}">Пред.</a></li>
    {% else %}
    <li class="page-item disabled"><a class="page-link" href="#">Пред.</a></li>
    {% endif %}
  {% for i in contact_list.paginator.page_range %}
      {% if contact_list.number == i %}
     <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?{% param_replace page=i %}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if contact_list.has_next %}
      <li class="page-item"><a class="page-link"  href="?{% param_replace page=contact_list.next_page_number %}">След.</a></li>
    {% else %}
    <li class="page-item disabled"><a class="page-link" href="#">След.</a></li>
    {% endif %}
  </ul>
</nav>
{% endif %}
    </div>
  </div>
{% endblock %}

src/sales/templates/sales/contactsource_list.html
{% extends 'base.html' %}

{% block container %}

<h1>Источники контактов</h1>

<a href="{% url 'sales:create_contact_source' %}"> Добавить новый</a>

    <table class="table table-striped">
  <thead>
    <tr>

      <th scope="col">Название</th>
      <th scope="col">Описание</th>
      <th scope="col">Потенциальные профили контактов</th>
      <th scope="col">Количество контактов</th>

    </tr>
  </thead>
  <tbody>

{% for c in contactsource_list %}
    <tr>

      <td>{{ c.name }} </td>
      <td>{{ c.description }}</td>
      <td>{% for p in  c.potential_profiles.all %} {{p}} {%endfor%}</td>
      <td>{{ c.contact_set.count }}</td>

    </tr>
{% endfor %}
  </tbody>
</table>
{% endblock %}

src/sales/templates/sales/delegate_list.html
{% extends 'base.html' %}
{% load tags %}

{% block container %}
<form action="" method="get" class="search-form" style="display:none">
  <div class="row"><div class="col-md-4">
  {% for field in filter.form %}

    {%if forloop.counter|divisibleby:"8" %}
      </div><div class="col-md-4">
    {%endif%}
  <div class="form-group">
    <label for="">{{field.label}}</label>
   {{field}}
  </div>
{%endfor%}
</div></div>
  <button type="submit">Поиск</button>

</form>
<p><button onclick="$('.search-form').toggle()">Фильтр</button> Всего: <b>{{filter.qs.count}}</b></p>
<script>


   $("#id_start_date").datetimepicker({
      timepicker:false,
      format:'m/d/Y',
      lang:'ru'
    });

    $("#id_end_date").datetimepicker({
      timepicker:false,
      format:'m/d/Y',
      lang:'ru'
    });
 </script>


{% if contact_list.has_other_pages %}
<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if contact_list.has_previous %}
    <li class="page-item"><a class="page-link" href="?{% param_replace page=contact_list.previous_page_number %}">Пред.</a></li>
    {% else %}
    <li class="page-item disabled"><a class="page-link" href="#">Пред.</a></li>
    {% endif %}
  {% for i in contact_list.paginator.page_range %}
      {% if contact_list.number == i %}
     <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?{% param_replace page=i %}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if contact_list.has_next %}
      <li class="page-item"><a class="page-link"  href="?{% param_replace page=contact_list.next_page_number %}">След.</a></li>
    {% else %}
    <li class="page-item disabled"><a class="page-link" href="#">След.</a></li>
    {% endif %}
  </ul>
</nav>
{% endif %}
<div class="row">
    <div class="col-md-6">
        <form action="" method="post" id="delegate">
            {% csrf_token %}
            <input type="hidden" name="cids" id="cids">
            <input type="submit"  value="Изменить агента" >
            {{agent_form}}

        </form>
    </div>
</div>

    <script>
        var csrf_token = "";
        $("form#delegate").on("submit",function(){
            var x = $("table tbody input[type=checkbox]");
            var data = data = $.map(x,function(el) { if (el.checked==true)  { return el.id; }});
            $("#cids").val(data.join(","));
            return true;
        });
        <!--$("#num").change(function(){-->
             <!--var item = $(this);-->
             <!--window.location.href = window.location.href.replace(/(num=)[^\&]+/, '$1' + item.val());-->
        <!--});-->
    </script>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Имя</th>
        <th scope="col">Агент</th>
        <th scope="col">Добавлен</th>
        <th scope="col">Источник</th>
        <th scope="col">Резюме</th>
        <th scope="col">Статус</th>
        <th scope="col"> <input type="checkbox"  onchange="checkAll(this.checked)">Выбрать</input></th>
    </tr>
  </thead>
  <tbody>

{% for c in contact_list%}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
        <td><a href="{% url 'sales:update_contact' c.id  %}?index={{forloop.counter0}}&contacts_id_list={{contacts_id_list}}&count={{count}}">{{ c.first_name}}  {{ c.last_name }}</a></td>
        <td>{{ c.agent.user.name }}</td>
        <td><a href="{% url 'sales:update_contact' c.id  %}?index={{forloop.counter0}}&contacts_id_list={{contacts_id_list}}&count={{count}}">{{ c.created_at|date:"d.m.y" }}</a></td>
        <td>{{c.source}}</td>
        <td><a href="{{c.cv_url}}">{{c.cv_title}}</a></td>
        <td>{{ c.lead_quality }}</td>
      <td><input type="checkbox" id="{{ c.pk }}"></td>
    </tr>
{% endfor %}
  </tbody>
</table>

  <script>
     function checkAll(c) {
         var checkboxes = document.querySelectorAll("table tbody input[type=checkbox]");
         for (var i = 0; i < checkboxes.length; i++) {
            checkboxes[i].checked = c;
           }
 }
  </script>
{% endblock %}

src/sales/templates/sales/int_form.html
{% load crispy_forms_tags %}
 {% if int_form.errors %}
    {% for field in int_form %}
        {% for error in field.errors %}
<div class="alert alert-danger" xmlns="http://www.w3.org/1999/html">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in int_form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<div class="col-md-7">
  <form method="post" id="add_interaction" enctype="multipart/form-data">
        {% csrf_token %}

       <div class="form-row">
          <div class="form-group col-md-9 mb-0">
            {{ int_form.result|as_crispy_field }}
          </div>
           <div class="form-group col-md-3 mb-0">
            {{ int_form.type|as_crispy_field }}
          </div>
       </div>

      <div class="form-row">
          <div class="form-group col-md-9 mb-0">
            <label for="sel1">При продаже выберите вакансию:</label>
          <select  class="form-control" id="vac_id" name="vac_id">
            <option value="nosale">---</option>
            {% for p in positions %}
            <option value="{{p.id}}">{{p.position_title}}</option>
            {% endfor %}
          </select>
          </div>
           <div class="form-group col-md-3 mb-0">
            {{ int_form.date|as_crispy_field }}
          </div>
       </div>

      <div class="form-group">

      </div>
  <button type="submit" class="btn btn-primary"> Добавить Звонок</button>
   {% if previous_contact %}
    <a href="{% url 'sales:update_contact' previous_contact  %}?index={{index|add:"-1"}}&contacts_id_list={{contacts_id_list}}&count={{count}}" class="btn btn-primary">Предыдущий контакт</a>
   {% endif%}
  {% if next_contact %}
    <a href="{% url 'sales:update_contact' next_contact  %}?index={{index|add:"1"}}&contacts_id_list={{contacts_id_list}}&count={{count}}" class="btn btn-primary">Следующий контакт</a>
  {% endif%}

  </form>
 <script>
    jQuery('#id_date').datetimepicker({
      format:'Y-m-d H:i',
      lang:'ru'
});

  </script>

</div>

<div class="col-md-5">
    <h4>Хронология</h4>
    <ul class="timeline">
        {% for i in interactions reversed %}
        <li>
            <p><b>{{i.agent.name }} {{i.interaction_date |date:"d-m-Y"}}</b></p>
            <p>{{i.result}}</p>
            <p>{% if i.order %}<b>Продажа:</b> {{i.order.vacancy}} {% endif %}</p>
        </li>
        {% endfor %}

    </ul>
</div>

src/sales/templates/sales/interactions.html
{% extends 'base.html' %}
{% block container %}
{% load crispy_forms_tags %}

<div class="row">
<div class="col-md-6">
  <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form | crispy}}
      <div class="form-group">
          <label for="sel1">При продаже выберите вакансию:</label>
          <select  class="form-control" id="vac_id" name="vac_id">
            <option value="nosale">---</option>
            {% for p in positions %}
            <option value="{{p.id}}">{{p.position_title}}</option>
            {% endfor %}
          </select>
      </div>
  <button type="submit" class="btn btn-primary"> Добавить</button>
  </form>
          <a href="{% url 'sales:update_contact' сontact.id %}">Редактировать контакт</a>

</div>

<div class="col-md-6">
    <h4>Хронология</h4>
    <ul class="timeline">
        {% for i in interactions reversed %}
        <li>
            <p><b>{{i.agent.name }} {{i.interaction_date |date:"d-m-Y"}}</b></p>
            <p>{{i.result}}</p>
            <p>{% if i.order %}<b>Продажа:</b> {{i.order.vacancy}} {% endif %}</p>
        </li>
        {% endfor %}

    </ul>
</div>

</div>



  <script>
    jQuery('#id_date').datetimepicker({
      format:'Y-m-d H:i',
      lang:'ru'
});

  </script>


{% endblock container %}

src/sales/templates/sales/manage_list.html
{% extends 'base.html' %}

{% block container %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="file">
    <select name="source" id="">
        {% for s in sources %}
            <option value="{{s.id}}">{{s.name}}</option>
        {% endfor %}

    </select>

    <button type="submit">Загрузить</button>
  </form>

{% if contact_list.has_other_pages %}
<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if contact_list.has_previous %}

    <li class="page-item"><a class="page-link" href="?page={{ contact_list.previous_page_number }}">Пред.</a></li>
    {% else %}
    <li class="page-item disabled"><a class="page-link" href="#">Пред.</a></li>
    {% endif %}
  {% for i in contact_list.paginator.page_range %}
      {% if contact_list.number == i %}
     <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
     {% if contact_list.has_next %}
      <li class="page-item"><a class="page-link"  href="?page={{ contact_list.next_page_number }}">Cлед.</a></li>
    {% else %}

    <li class="page-item disabled"><a class="page-link" href="#">Cлед.</a></li>
    {% endif %}

  </ul>
{% endif %}

    <!--<script>-->
        <!--$("#num").change(function(){-->
             <!--var item = $(this);-->
             <!--url = window.location.href-->
             <!--if(url.indexOf("?" == -1)) {-->
                <!--url = url + "?num=1"-->
             <!--} else if (url.indexOf("page=" != -1)) {-->
                <!--url = url + "&num=1"-->
             <!--}-->
             <!--window.location.href = url.replace(/(num=)[^\&]+/, '$1' + item.val());-->


        <!--});-->
    <!--</script>-->

<form action="" method="post" id="delegate">
    {% csrf_token %}
    <input type="hidden" name="cids" id="cids">
    <input type="submit"  value="В продажи" >
</form>

    <script>
            var csrf_token = "";
        $("form#delegate").on("submit",function(){
            var x = $("table input[type=checkbox]");
            var data = data = $.map(x,function(el) { if (el.checked==true)  { return el.id; }});
            $("#cids").val(data.join(","));
            return true;
        });
        $("#num").change(function(){
             var item = $(this);
             window.location.href = window.location.href.replace(/(num=)[^\&]+/, '$1' + item.val());
        });
    </script>
    <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Имя</th>
      <th scope="col">В продажах</th>
      <th scope="col">Источник</th>
      <th scope="col">Выбрать</th>
    </tr>
  </thead>
  <tbody>

{% for c in contact_list%}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
        <td><a href="{% url 'sales:interactions' c.id  %}">{{ c.first_name}}  {{ c.last_name }}</a></td>
      <td>{{ c.in_sales }}</td>
      <td>{{ c.source }}</td>
       <td><input type="checkbox" id="{{ c.pk }}"></td>
    </tr>
{% endfor %}
  </tbody>
</table>
{% endblock %}