src/employer/urls.py
from django.urls import path
from .views import *


app_name = "employer"
urlpatterns = [
    path("<id>/vacancy/create", CreateVacancy.as_view(), name="vacancy_create"),
    path("<id>/vacancy/", VacancyList.as_view(), name="vacancy_list"),
    path("vacancy/", VacancyList.as_view(), name="all_vacancies"),
    path("vacancy/<id>", vacancy_detail, name="vacancy_detail"),
    path("vacancy/<id>/edit", vacancy_edit, name="vacancy_edit"),
    path("", EmployerList.as_view(), name="employers_list"),
    path("create/", CreateEmployer.as_view(), name="employer_create"),
    path("<id>/contacts/", CreateContactPerson.as_view(), name="employer_contact_create"),
    path("<pk>/", EmployerDetail.as_view(), name="employer_detail"),
    path("create_expense/", CreateExpense.as_view(), name="create_expense"),
    path("expenses_list/", expenses_list, name="expenses_list"),
    path("create_note/employer/", employer_create_note, name='employer_create_note'),
    path("create_note/vacancy/", employer_create_note, name='vacancy_create_note'),
    path("create_note/agent/", employer_create_note, name='agent_create_note'),
]

src/sales/urls.py
from django.urls import path
from django.conf.urls import url
from .views import *
from . import views

app_name = "sales"
urlpatterns = [
    path("contact_list", contact_list, name="contact_list"),
    path("delegate_list", delegate_list, name="delegate_list"),
    path("create_contact", create_contact, name="create_contact"),
    path("postback", postback, name="postback"),
    path("update_contact/<id>", update_contact1, name="update_contact"),
    path("update_contact1/<id>", update_contact1, name="update_contact1"),
    path("interactions/<id>", interactions, name="interactions"),
    path("interactions1/<id>", interactions1, name="interactions1"),
    path("manage_list", manage_list, name="manage_list"),
    path("order_list", order_list, name="order_list"),
    path("agent_stats", agent_stats, name="agent_stats"),
    path("contact_source_list", ContactSourceList.as_view(), name="contact_source_list"),
    path("create_contact_source", create_contact_source, name="create_contact_source"),
    path("postback", postback_handle, name="postback_handle"),
    path("create_profile", create_profile, name="create_profile"),
]

src/employer/models.py
from django.db import models

class Vacancy(models.Model):
    employer = models.ForeignKey("Employer", on_delete=models.CASCADE, verbose_name="Провайдер")
    position_title = models.CharField(max_length=580, verbose_name="Название вакансии")
    employer_name = models.CharField(max_length=80, blank=True, verbose_name="Название работодателя")
    employer_description = models.CharField(max_length=400, blank=True, verbose_name="Описание компании работодателя")
    job_description = models.CharField(max_length=1000, blank=True, verbose_name="Описание работы")
    requirements = models.CharField(max_length=500, blank=True, verbose_name="Требования к работнику")
    employee_count = models.CharField(max_length=200, blank=True, verbose_name="Необходимое количество работников")
    employee_count_add = models.CharField(max_length=200, blank=True, verbose_name="Дополнительно - Необходимое количество работников")

    city = models.CharField(max_length=200, blank=True, verbose_name="Город работы")
    start_date = models.DateField(max_length=200, blank=True, verbose_name="Дата старта")
    start_date_add = models.CharField(max_length=200, blank=True, verbose_name="Дополнительно - Дата старта")
    working_days = models.CharField(max_length=500, blank=True, verbose_name="Дни работы")
    working_days_add = models.CharField(max_length=500, blank=True, verbose_name="Дополнительно - Дни работы")
    work_schedule = models.CharField(max_length=500, blank=True, verbose_name="График работы")
    work_schedule_add = models.CharField(max_length=500, blank=True, verbose_name="Дополнительно - График работы")
    living_price = models.CharField(max_length=200, blank=True, verbose_name="Стоимость проживания")
    living_price_add = models.CharField(max_length=200, blank=True, verbose_name="Дополнительно - Стоимость проживания")
    living_conditions = models.CharField(max_length=800, blank=True, verbose_name="Условия проживания")
    trial_duration = models.CharField(max_length=200, blank=True, verbose_name="Длительность испытательного срока")
    trial_duration_add = models.CharField(max_length=200, blank=True, verbose_name="Дополнительно - Длительность испытательного срока")
    trial_salary = models.CharField(max_length=200, blank=True, verbose_name="Зарплата во время испытательного срока")
    salary = models.CharField(max_length=200, blank=True, verbose_name="Зарплата после испытательного срока")
    salary_after_year = models.CharField(max_length=500, blank=True, verbose_name="Зарплата через год")
    overtime_hours = models.CharField(max_length=500, blank=True, verbose_name="Максимальное количество рабочих часов")
    entering_bonus = models.CharField(max_length=500, blank=True, verbose_name="Бонус при выходе на работу")
    year_bonus = models.CharField(max_length=500, blank=True, verbose_name="Годовой бонус")
    career_opportunities = models.CharField(max_length=20, blank=True, verbose_name="Возможности карьерного роста")
    status = models.CharField(max_length=200, blank=True, default="active",  verbose_name="Статус", choices=(("active","Активная"),("hold","Приостановленная"),("archive","Архивная")))
    documents = models.CharField(max_length=200, blank=True, verbose_name="Документы", choices=(("Виза 3 мес","Виза 3 мес"),("Виза 1 год","Виза 1 год"),("Рабочая карта","Рабочая карта"),
                                                                      ("Виза 3 месяца + Карта","Виза 3 месяца + Карта"),("Виза 1 год + Карта","Виза 1 год + Карта"), ("Биометрия + ВНЖ", "Биометрия + ВНЖ")))
    documents_add = models.CharField(max_length=200, blank=True, verbose_name="Дополнительно - Документы")
    price = models.IntegerField(verbose_name="Стоимость вакансии")
    price_add = models.CharField(verbose_name="Дополнительно - Стоимость вакансии", blank=True, max_length=200)
    for_pairs = models.BooleanField(default=False, verbose_name="Для семейных пар")
    for_pairs_add = models.CharField(max_length=200, blank=True, verbose_name="Дополнительно - Для семейных пар")

    def __str__(self):
        return self.position_title


class Employer(models.Model):
    company_name = models.CharField(max_length=50, blank=True)
    country = models.CharField(max_length=50, blank=True)
    office_address = models.CharField(max_length=50, blank=True)
    site = models.CharField(max_length=50, blank=True)
    def __str__(self):
        return self.company_name


class ContactPerson(models.Model):
    name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50, blank=True)
    email = models.EmailField(max_length=50, blank=True)
    role = models.CharField(max_length=50, blank=True)
    employer = models.ForeignKey(Employer, on_delete=models.CASCADE)
    languages = models.ManyToManyField('Language')

    def __str__(self):
        return self.name


class Language(models.Model):
    language = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.language


class Expenses(models.Model):
    type_of_expense = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.type_of_expense


class HistoryExpense(models.Model):
    date_of_expense = models.DateField(max_length=30, blank=True)
    sum_of_expense = models.IntegerField(blank=True)
    expense = models.ForeignKey(Expenses, on_delete=models.CASCADE)


class Note(models.Model):
    headline = models.CharField(max_length=200, blank=True)
    text = models.CharField(max_length=200, blank=True)

    class Meta:
        abstract = True


class VacancyNote(Note):
    vacancy = models.ForeignKey(Vacancy, on_delete=models.CASCADE)


class EmployerNote(Note):
    employer = models.ForeignKey(Employer, on_delete=models.CASCADE)


class AgentNote(Note):
    agent = models.ForeignKey(ContactPerson, on_delete=models.CASCADE)

src/employer/forms.py
from django import forms
from .models import *


class VacancyForm(forms.ModelForm):
    class Meta:
        model = Vacancy
        fields = '__all__'
        widgets = {
            'job_description': forms.Textarea(attrs={'cols': 50, 'rows': 12}),
            'employer_description': forms.Textarea(attrs={'cols': 50, 'rows': 8}),
            'living_conditions': forms.Textarea(attrs={'cols': 50, 'rows': 5}),
            'requirements': forms.Textarea(attrs={'cols': 50, 'rows': 8}),
            'career_opportunities': forms.Textarea(attrs={'cols': 50, 'rows': 5}),
        }


class CreateEmployerForm(forms.ModelForm):
    class Meta:
        model = Employer
        fields = '__all__'


class CreateContactPersonForm(forms.ModelForm):
    languages = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple(),
                                               queryset=Language.objects.all())

    class Meta:
        model = ContactPerson
        fields = '__all__'


class CreateExpenseForm(forms.ModelForm):
    class Meta:
        model = Expenses
        fields = '__all__'


class CreateNoteForm(forms.ModelForm):
    class Meta:
        model = EmployerNote
        fields = '__all__'

src/employer/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, AccessMixin, PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect

from .forms import *
from django.views.generic import TemplateView, ListView, DetailView, CreateView
from django.http import HttpResponseRedirect


def perm(permission=''):
    class PermissionMixin(PermissionRequiredMixin):
        permission_required = permission

        def handle_no_permission(self):
            return redirect('/')
    return PermissionMixin


class CreateVacancy(perm('auth.director'), TemplateView):
    form = VacancyForm
    template_name = 'create_vacancy_form.html'

    def get(self, request, id):
        form = self.form()
        form.fields["employer"].initial = id
        return render(request, self.template_name, context={'form': form})

    def post(self, request, id):
        form = self.form(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/employer/')
        return render(request, self.template_name, context={'form': form})


class CreateEmployer(perm('auth.director'), CreateView):
    template_name = 'create_employer_form.html'
    form_class = CreateEmployerForm
    success_url = "/"


class EmployerDetail(perm('auth.director'), DetailView):
    model = Employer
    slug_field = 'id'


class EmployerList(perm('auth.director'), ListView):
    model = Employer


class VacancyList(perm('auth.agent'), ListView):
    model = Vacancy

    def get_queryset(self):
        queryset = Vacancy.objects.all()
        if "id" in self.kwargs:
            queryset = Vacancy.objects.filter(employer__pk=self.kwargs["id"])
        return queryset

class CreateContactPerson(perm('auth.director'), TemplateView):
    form = CreateContactPersonForm
    template_name = 'create_contact_person_form.html'

    def get(self, request, id):
        form = self.form()
        return render(request, self.template_name, context={'form': form})

    def post(self, request, id):
        form = self.form(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
        return render(request, self.template_name, context={'form': form})

class CreateExpense(perm('auth.director'),TemplateView):
    form = CreateExpenseForm
    template_name = 'create_expense.html'

    def get(self, request):
        form = self.form()
        return render(request, self.template_name, context={'form': form})

    def post(self, request):
        form = self.form(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
        return render(request, self.template_name, context={'form': form})


@permission_required('auth.director')
def expenses_list(request):
    expenses = Expenses.objects.all()
    return render(request, 'expenses_list.html', context={'expenses': expenses})


@permission_required('auth.director')
def vacancy_create_note(request):
    if request.method == 'POST':
        note_form = CreateNoteForm(request.POST)
        if note_form.is_valid():
            note = note_form.save()
            note.save()
        return redirect(request, 'vacancy_note.html', pk=note.pk)


@permission_required('auth.director')
def employer_create_note(request):
    if request.method == 'POST':
        note_form = CreateNoteForm(request.POST)
        if note_form.is_valid():
            note = note_form.save()
            note.save()
        return redirect(request, 'employer_note.html', pk=note.pk)


@permission_required('auth.superagent')
def agent_create_note(request):
    if request.method == 'POST':
        note_form = CreateNoteForm(request.POST)
        if note_form.is_valid():
            note = note_form.save()
            note.save()
        return redirect(request, 'agent_note.html', pk=note.pk)


@permission_required('auth.agent')
def vacancy_detail(r, id):
    vacancy = Vacancy.objects.get(pk=id)
    return render(r, 'employer/vacancy_detail.html', context={'v': vacancy})


@permission_required('auth.director')
def vacancy_edit(r, id):
    vacancy = Vacancy.objects.get(pk=id)
    if r.method == 'POST':
        form = VacancyForm(r.POST, instance=vacancy)
        if form.is_valid():
            form.save()
    return render(r, 'create_vacancy_form.html', context={'form': VacancyForm(instance=vacancy)})

src/employer/templates/employer/employer_detail.html
{% extends 'base.html' %}

{% block container %}
    <h1 class="h3 mb-2 text-gray-800"> Работодатель {{ employer.company_name }} </h1>
    
    <p>
        {{ employer.country }}
        {{ employer.site }}
    </p>

<a href="{% url 'employer:vacancy_create' employer.id %}">Добавить вакансию</a>

{% endblock container %}

src/employer/templates/employer/employer_list.html
{% extends 'base.html' %}

{% block container %}
    <h1 style="margin-top: 5%;">Список Провайдеров</h1>
<a href="{% url 'employer:employer_create' %}">Добавить провайдера</a>
        {% for employer in employer_list %}
            <p>
                <a href="{% url 'employer:employer_detail' pk=employer.id  %}">{{ employer.company_name }}</a>
                {{ employer.country }}
            </p>
        {% endfor %}
{% endblock container %}

src/employer/templates/employer/vacancy_detail.html
{% extends 'base.html' %}

{% block container %}
    <h1 class="h3 mb-2 text-gray-800"> Вакансия {{ v.position_title }} </h1>
<a href="{% url 'employer:vacancy_edit' v.id %}"> Изменить</a>
    <div class="row">
        <div class="col-md-10">
            <table class="table table-striped">
  <thead>
    <tr>
<th  style="width: 20%" >Название</th>
      <th   style="width: 80%">Описание</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td >Провайдер</td><td>{{v.provider}}</td>
    </tr>
    <tr>
      <td>Статус</td><td>{{v.status}}</td>
    </tr>
    <tr>
      <td>Семейные Пары</td><td>{{ v.for_pairs|yesno:"Да,Нет" }}</td>
    </tr>
    <tr>
      <td>Цена</td><td>{{v.price}} Евро</td>
    </tr>
    <tr>
      <td>Документы</td><td>{{v.documents}}</td>
    </tr>
    <tr>
      <td>Работодатель</td><td>{{v.employer_name}}</td>
    </tr>
    <tr>
        <td>Дата старта</td> <td>{{v.start_date}}</td>
    </tr>

    <tr>
        <td>Город</td> <td>{{v.city}}</td>
    </tr>
    <tr>
  <td>Количество работников</td> <td>{{v.employee_count}}</td>
  </tr>
  <tr>
        <td>Зарплата</td> <td>{{v.salary}}</td>
    </tr>
  <tr>
        <td>Зарплата во время испытательного срока</td> <td>{{v.salary_after_trial}}</td>
    </tr>
  <tr>
        <td>Длительность испытательного срока</td> <td>{{v.trial_duration}}</td>
    </tr>
  <tr>
        <td>Зарплата через год</td> <td>{{v.salary_after_year}}</td>
    </tr>
    <tr>
        <td>Бонус при выходе на работу</td> <td>{{v.entering_bonus}}</td>
    </tr>
    <tr>
        <td>Годовой бонус</td> <td>{{v.year_bonus}}</td>
    </tr>
    <tr>
        <td>Возможности карьерного роста</td> <td>{{v.career_opportunities}}</td>
    </tr>
  <tr>
        <td>Дни работы</td> <td>{{v.working_days}}</td>
    </tr>
  <tr>
        <td>График работы</td> <td>{{v.work_schedule}}</td>
    </tr>
  <tr>
        <td>Стоимость проживания</td> <td>{{v.living_price}}</td>
    </tr>  
    <tr>
        <td>Описание работы</td> <td>{{v.job_description}}</td>
    </tr>
                 <tr>
        <td>Требование к работнику </td> <td>{{v.requirements}}</td>
    </tr>
  </table>

        </div>
    </div>


{% endblock container %}

src/employer/templates/employer/vacancy_list.html
{% extends 'base.html' %}

{% block container %}
    <h1 style="margin-top: 5%;">Список Вакансий</h1>

{% if vacancy_list.has_other_pages %}
<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if vacancy_list.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{ vacancy_list.previous_page_number }}">Пред.</a></li>
    {% else %}
    <li class="page-item disabled"><a class="page-link" href="#">Пред.</a></li>
    {% endif %}
  {% for i in vacancy_list.paginator.page_range %}
      {% if vacancy_list.number == i %}
     <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
     {% if vacancy_list.has_next %}
      <li class="page-item"><a class="page-link"  href="?page={{ vacancy_list.next_page_number }}">Cлед.</a></li>
    {% else %}
    <li class="page-item disabled"><a class="page-link" href="#">Cлед.</a></li>
    {% endif %}
  </ul>
{% endif %}



    <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Название</th>
      <th scope="col">Провайдер</th>
      <th scope="col">Работодатель</th>
      <th scope="col">Старт работы</th>
      <th scope="col">Количество работников</th>
      <th scope="col">Семейные Пары</th>
      <th scope="col">Тип документов</th>
      <th scope="col">Зарплата</th>
      <th scope="col">Цена</th>
    </tr>
  </thead>
  <tbody>

{% for v in vacancy_list%}

<tr>
      <th scope="row">{{v.id}}</th>
      <td><a href="{% url 'employer:vacancy_detail' v.id %}">{{ v.position_title }}</a> </td>
      <td>{{ v.employer }}</td>
      <td>{{ v.employer_name }}</td>
      <td>{{ v.start_date }}</td>
      <td>{{ v.employee_count }}</td>
      <td>{{ v.for_pairs|yesno:"Да,Нет" }}</td>
      <td>{{ v.documents }}</td>
      <td>{{ v.salary }}</td>
      <td>{{ v.price }}</td>
</tr>

{%endfor%}

</tbody>
</table>

{% endblock container %}